name: Survival
version: '${project.version}'
main: me.scaffus.survival.Survival
api-version: 1.19
load: STARTUP

commands:
  openmenu:
    aliases: [ "om", "omenu", "openm" ]
    description: Opens the specified menu
  reloadmenus:
    aliases: [ "rm", "rmenus", "reloadm" ]
    description: Reloads all menus
  listmenus:
    aliases: [ "lm", "lmenus", "listm" ]
    description: Lists all menus
  item:
    aliases: [ "im" ]
    description: Gives the specified item
  listitems:
    aliases: [ "li", "litems", "listi" ]
    description: Lists all items
  reloadconfigs:
    aliases: [ "rc", "rconfigs", "reloadc" ]
    description: Reloads all configs
  detail:
    description: Shows the item in hand's details
  bank:
    description: Opens the bank menu
  message:
    aliases: [ "msg", "w", "tell" ]
    description: Send a private message to a player
#    survival:
#        description: Survival plugin
#        usage: /<command>
#        aliases: [survival]
#        permission: survival.command
#        permission-message: You don't have permission to use this command